services:
  minecraft:
    build: .
    image: minecraft-neoforge
    container_name: minecraft-neoforge
    restart: unless-stopped
    environment:
      - MIN_RAM=4G
      - MAX_RAM=8G
      - EULA=TRUE
    volumes:
      - ./world:/server/world
      - ./config:/server/config
      - ./mods:/server/mods
      - ./resource_packs:/server/resource_packs
      - ./behavior_packs:/server/behavior_packs
      - ./backups:/server/backups
    ports:
      - "25565:25565"
      - "19132:19132/udp"