bedrock:
  address: 0.0.0.0
  port: 19132
  motd1: "NeoForge Server"
  motd2: "Java+Bedrock Crossplay"

remote:
  address: 127.0.0.1
  port: 25565
  auth-type: floodgate

floodgate-key-file: ./config/floodgate/key.pem

command-suggestions: true

passthrough-motd: true
passthrough-player-counts: true
legacy-ping-passthrough: false

ping-passthrough-interval: 3

max-players: 20

debug-mode: false
general-thread-pool: 32

allow-third-party-capes: true
allow-third-party-ears: false
show-cooldown: true

scoreboard-packet-threshold: 20

enable-proxy-connections: false